name: Streamtape windows

on:
  workflow_dispatch:
  schedule:
    #- cron: '0,10,20,30,40,50 * * * *'
     - cron: '*/11 * * * *'


jobs:
  capture_screenshots:
    strategy:
      matrix:
        runs-on: [windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest, windows-latest]  # 7 instances
    runs-on: ${{ matrix.runs-on }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'
        
      - name: Install dependencies
        run: pip install undetected-chromedriver selenium pyvirtualdisplay pyautogui fake-useragent chromedriver_autoinstaller

      - name: Run Selenium script
        run: python stream.py
        
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: '**/*.png'
