name: Streamtape mac

on:
  workflow_dispatch:
  # schedule:
  #    - cron: '*/19 * * * *'


jobs:
  capture_screenshots:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'
        
      - name: Install dependencies
        run: pip install undetected-chromedriver selenium pyvirtualdisplay pyautogui fake-useragent

      - name: Run Selenium script
        run: python stream.py
        
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: '**/*.png'
